name: cd
on:
  workflow_dispatch:
jobs:
  semantic-release:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
          private_key: ${{ secrets.SEMANTIC_RELEASE_PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - uses: node/setup-node@v4
        with:
          node-version: 24
      - run: npm ci
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

